# ----------------------------------------------------------------------------
[univariate]
[univariate.make_spline]

[[univariate.make_spline.parameters]]
size = [10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000,
        25000, 50000, 75000, 100000, 250000, 500000, 1000000]


# ----------------------------------------------------------------------------
[multivariate]
[multivariate.make_spline]

[[multivariate.make_spline.parameters]]
size = [10, 50, 100, 500, 1000, 5000]

[[multivariate.make_spline.parameters]]
ndim = [2, 3, 4, 5, 6, 7, 8, 9, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000]
